name: 1.1 Fork Deploy Stub

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  comment-landing-url:
    if: ${{ github.repository_owner == github.actor }}
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR with landing page URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const url = "https://main-sd-preprod.dev.essr.ch/";
            const commentBody = `🚀 This pull request has been deployed to:\n\n🔗 ${url}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
